name: Deploy Image Guessing Game

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./spot-the-ball
          cname: ten-protocol.github.io/sample-applications/spot-the-ball/
          commit_message: Deploy Image Guessing Game
